lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  alias StorexWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Cart
    plug Plugs.ItemsCount
    plug Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index

    resources "/books", BookController
    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
    resources "/checkout", CheckoutController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex/sales/cart.ex
defmodule Storex.Sales.Cart do
  use Ecto.Schema
  import Ecto.Changeset
  alias Storex.Sales.Cart


  schema "sales_carts" do
    has_many :line_items, Storex.Sales.LineItem
    timestamps()
  end

  @doc false
  def changeset(%Cart{} = cart, attrs) do
    cart
    |> cast(attrs, [])
    |> validate_required([])
  end
end

lib/storex_web/controllers/cart_controller.ex
defmodule StorexWeb.CartController do
  use StorexWeb, :controller
  
  alias StorexWeb.Plugs
  alias Storex.Sales
  alias Storex.Store

  def show(conn, _params) do
    cart = Plugs.Cart.get(conn)
    items = Sales.list_line_items(cart)
    total = Sales.line_items_total_price(items)
    render conn, "show.html", items: items, total: total
  end

  def create(conn, %{"book_id" => book_id}) do
    cart = Plugs.Cart.get(conn)
    book = Store.get_book(book_id)
    Sales.add_book_to_cart(book, cart)

    redirect(conn, to: cart_path(conn, :show))
  end

  def delete(conn, %{"book_id" => book_id}) do
    cart = Plugs.Cart.get(conn)
    book = Store.get_book(book_id)
    Sales.remove_book_from_cart(book, cart)

    redirect(conn, to: cart_path(conn, :show))
  end
end

lib/storex_web/views/cart_view.ex
defmodule StorexWeb.CartView do
  use StorexWeb, :view

  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/templates/cart/show.html.eex
<h1>Your cart</h1>

<ul class="cart-items">
  <%= for item <- @items do %>
    <li class="cart-item">
      <img class="cart-item__image" src="<%= item.book.image_url %>">
      <div class="cart-item__title">
        <span><%= item.book.title %></span>
      </div>

      <div class="cart-item__units">
        <div class="value-tag">
          <h2 class="value-tag__title">quantity<h2>
          <span class="value-tag__content">
            <div class="step minus">
              <%= link "-", to: cart_path(@conn, :delete, book_id: item.book_id), method: :delete %>
            </div>
            <%= item.quantity %>
            <div class="step plus">
              <%= link "+", to: cart_path(@conn, :create, book_id: item.book_id), method: :create %>
            </div>
          </span>
        </div>
      </div>
      <div class="cart-item__price">
        <div class="value-tag">
          <h2 class="value-tag__title">price</h2>
          <span class="value-tag__content">
            <%= format_price(item.book.price) %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<div class="value-tag">
  <h2 class="value-tag__title">total</h2>
  <span class="value-tag__content"><%= format_price(@total) %></span>
</div>

<%= link "Checkout", to: checkout_path(@conn, :new), class: "button button-primary" %>